# Generated by Django 3.2.9 on 2022-12-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, verbose_name='Nom')),
                ('user_id', models.CharField(max_length=50, verbose_name='Numéro de carte')),
                ('is_present', models.BooleanField(verbose_name='Présent')),
            ],
        ),
    ]
