# Generated by Django 3.2.9 on 2022-12-09 02:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='hour_of_presence',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Heure de la présence'),
        ),
    ]
